### PR TITLE
URL constants and moving databases across stages

### LINKED ISSUE #35: Stop Setting the URL Constants
I've found an issue with setting the `WP_HOMEURL` and `WP_SITEURL` constants in the `wp-config.php` file. When `site_url();` or `home_url();` are called within the theme they fail to output the actual url (either nothing at all or just `/wp`). It seems we've been through [this before with Genesis](https://github.com/genesis/wordpress/commit/e2afba80d35800ee13b0a9c0dbef60a2b56dd724) but I'm not sure if that was changed for a different reason.

### PR DESCRIPTION
**Pull request by EvanK**
Relative URL constants have strange side effects ranging from non-fatal warnings in the admin to breaking poorly written plugins. The trade off was to be able to up/down databases between stages without worrying about hardcoded domains in the db data.

As a workaround, I've set the URL constants as absolute urls in wp-config, using the ~~`$_SERVER[HTTP_HOST]`~~ `$_SERVER[SERVER_NAME]` variable, and then added some ~~perl regex filtering~~ wp-cli string replacing of the dumped sql ~~before~~ after importing on db down/up operations.

Fixes #35 (I hope)

### CODE REVIEW

**Comment by EvanK** [comment]
@ericrasch @germanny Do y'all remember what wordpress features & plugins were breaking due to relative urls? I'd like to test this comprehensively before I consider it fixed

**Comment by germanny** [comment]
The BWP Google Sitemaps plugin - https://wordpress.org/plugins/bwp-google-xml-sitemaps/ - did not work with Evolution, and we believed that it was due to the site_url option having /wp there instead of the full URL. I can't remember exactly but I believe the urls out putted by the plugin were incorrect.

I am a little concerned what kind of SEO issues we're going to have with relative. We rely on Yoast SEO plugin to create canonical links for us, for example. Aren't these going to turn up as relative links now? According to advice from Google and Yoast, we want these and all the links on our sites to be absolute links, not relative. Canonical links _need_ to be absolute. And given the number of pages we have on some of our sites that are super super similar (ie, ./masters/, ./history/masters/, ./accounting/, ./accounting/careers/, ./careers/ - these types of very similar links and more existed at one time on sites like OEDb.org and certainly could return in the future), this is going to turn into a rabbit hole of relative urls that the content team isn't going to be able to manage easily nor are we going to be able to keep track of well. A [Yoast article](https://yoast.com/relative-urls-issues/) calls them "spider traps," and I'm a little worried that with the way we do business that could be a real issue.

I feel like there were a couple other issues but I can't find documentation on them so can't say what they were. Personally, I don't think it's nearly as big of a problem to do a couple very simple SQL queries or use a plugin or Screaming Frog to to identify and update the DB as needed with non-local or -staging urls. It's something that should be part of the dev's job and it literally takes 5 minutes to do.

Just my two cents.

**Comment by ericclemmons** [comment]
Wait, URLs _have_ to be absolute?  This reminds me of SEO debates we had @ WhiteFence nearly 10 years ago =/

It's not that the paths are _relative_, but they omit the `hostname`, since that's what's dynamic across environments.

That's why most application frameworks & the like generate URLs that are _paths_ (e.g. `/path/to/resource?id=123`), not absolute URLs including `hostname`.

Having a `<link rel="canonical">` in the dynamically set in satisfies the "SEO" correct?
> https://support.google.com/webmasters/answer/139066?hl=en

Genesis currently hacks the absolute URLs (via `ob_start` / `ob_flush`) with their correct version.  Doing a DB find/replace is also a hack.

I always felt the best solution (which is yet to be discovered in WordPress) is one that ensures resource URIs use paths, unless they're external.

But that's the thing, I'm trying to apply how applications are built to WordPress, which like trying to herd cats.  My patience for WordPress being suitable for this sort of workflow is strained at this point, so I'm cool to just back away & let ride whatever _works_ with the "architecture" we're stuck with...

**Comment by EvanK** [comment]
I'll test the sitemaps and yoast plugins, but I suspect the issue really was a relative url in the _runtime constants_ rather than urls saved in the database.

**Comment by EvanK** [comment]
Looks like there *are* still issues (plugin related) with relative urls in the database. To address this, I'm _replacing_ the stage subdomains via the regex filter...instead of converting them entirely to relative urls.

For example, on `production evolve:db:up`, instead of this:
`http://local.example.com/?p=1` -> `/?p=1`

We'll get this:
`http://local.example.com/?p=1` -> `http://production.example.com/?p=1`

**Comment by EvanK** [comment]
I think this latest couple commits will be a good fix! Here's what I've done:

* Apache is configured with a default canonical url of whatever bare domain the project is generated with (`example.com` in our test project). This means that regardless of whether the client sends a `Host:` header or hits the server directly by ip, we will _always_ have a ServerName set
* The Evolution php class is generated with the bare domain set as a constant, meaning we can match any stage subdomain (or none) anchored to the domain we know to look for...and we're matching against `SERVER_NAME` instead of `HTTP_HOST` -- [read more on why that's a sound security practice](http://stackoverflow.com/questions/2297403/http-host-vs-server-name#answer-2297421)
* The wp config is now setting absolute urls based on the environment and domain in the Evolution php class, so we end up with roughly homogenous absolute urls:
  * Host header of `local.example.com` has a siteurl of `http://local.example.com`
  * Host `feature-branch.staging.example.com` has `http://staging.example.com`
  * Host `production.example.com` has `http://example.com`
  * Host `www.example.com` has `http://example.com`
  * Host `example.com` has `http://example.com`

**Comment by germanny** [comment]
So will `http://example.com` be stored in the wpdb instead of `http://www.example.com`?

**Comment by EvanK** [comment]
@germanny Yes, the urls that are saved in the database come from the `WP_HOME` and `WP_SITEURL` constants.

By standardizing those, we can ensure that _any_ production activity will end up saving `example.com`, and that _any_ staging activity (even on a crazy vhost aliased branch) will save `staging.example.com`.

**Comment by germanny** [comment]
Slick! I'm think about 301s. If the site is meant to have `www.` in the link, but it's in the wpdb without, I wonder if that will come up as a 301?

**Comment by ericrasch** [comment]
We have only a handful of sites that _don't_ use `www.`. Most do include the `www.` and is also specified via Google Webmaster Tools to prefer the `www.` versions. Will this affect that (with 301s)?

Also was wondering about the staging sites and if we had multiple staging branches, how would those be affected? One branch might have a plugin installed that's not on the main staging branch. Will that break the site?

**Comment by EvanK** [comment]
I thought the bare domain (non-www) was preferred in most cases...but I can add a setting in the generator to set the canonical production domain way or the other.

As for 301s, it _shouldn't_ be redirecting the user at all (except when logging into the wp admin), but rather just serve as the requested hostname. That said, **the on-page links** will all be using the canonical stage-specific domain. I'd suppose that, for SEO purposes, a bare->www (or vice versa) redirect should exist in the root htaccess?

**Comment by EvanK** [comment]
Support for multiple staging branches is always going to be shaky, as **all staging branches share the same database**.  I believe Wordpress handles this as gracefully as possible though, deactivating plugins that are registered in the db but don't exist on the filesystem

**Comment by EvanK** [comment]
Okay, www vs non-www is configurable:
generator www prompt

Added a [rewrite rule to enforce it either way](https://github.com/evolution/wordpress/blob/35-url-constants/lib/yeoman/templates/web/_htaccess#L7), supports https too. In the process, added [support for preserving htaccess customizations](https://github.com/evolution/wordpress/blob/35-url-constants/lib/yeoman/index.js#L445)

**Comment by ericclemmons** [comment]
That's pretty legit!

**Comment by EvanK** [comment]
Yep! The only lingering issue here is:
* Requests to `production.example.com` or `www.example.com` still serve `example.com` links
* Requests to `branch.staging.example.com` still serve `staging.example.com` links

I'm not sure how to resolve this without output buffering...which I _really_ don't want to do...

**Comment by ericclemmons** [comment]
Hmmm... let me think on this one a bit...

**Comment by EvanK** [comment]
@ericclemmons Thinking about merging this, and opening a separate issue for the URL disparities on `production.*` and `*.staging.*`

**Pull request merged**
