### PR TITLE
Adding swapfile to provisioning

### PR DESCRIPTION
**Pull request by EvanK**
Provisioning evolution or genesis on digital ocean has resulted in mysql db crashes that I can only attribute to memory. Even with a 2Gb droplet, mysql was crapping the bed every so often with really minimal traffic, over time.

The way I "resolved" it in genesis was to add a swapfile like this:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-12-04

Recently deploying a 2Gb instance of evolution, I started having the same issues so I added swap to this ubutnu 14.04 vps, hoping it does the trick. Would it make sense to add a minimal (256) swap file to ansible provisioning?

Or related: have any of you had this experience? Looking through Digital Ocean support, quite a few people have wordpress/LAMP issues with mysql memory.

### CODE REVIEW

**Comment by EvanK** [comment]
Added a `swap.yml` playbook to the common role, that is included conditionally when `ansible_swaptotal_mb` is zero.

Within it, we are [calculating the ideal swapfile size by available memory and diskspace](https://github.com/evolution/wordpress/blob/83-create-swapfile/lib/ansible/roles/common/templates/swapsize.j2). On my vm with 4GB memory and 40GB disk, this creates a 7906M swapfile.

I've abstracted the swapfile path, `swappiness` and `vfs_cache_pressure` values to [group vars](https://github.com/evolution/wordpress/blob/83-create-swapfile/lib/yeoman/templates/lib/ansible/group_vars/all#L41-L44), which will require regeneration (and thus require a minor version bump).

Thoughts?

**Comment by mcheck** [comment]
This is really good, though twice the real RAM swapfile seems big for an
emergency buffer.

I was using half the real RAM as a swapfile size since I am setting
swappiness at 10 which will overflow (as I understand it) only when
physical memory approaches 80-90%.

Even on an SSD, swapfile exchange is expensive to performance and so I
wanted only a spillover for the cases where mysql craps the bed for
whatever reason.

**Comment by EvanK** [comment]
I was going on the recommendation from your Digital Ocean article:
> Generally, an amount equal to or double the amount of RAM on your system is a good starting point.

It's also defaulting swappiness to 10, to prevent its use except when physical memory is mostly utilized

**Comment by mcheck** [comment]
Ok. Maybe just equal to physical RAM? 

Thanks,

Michael Check
312-560-2321

**Comment by AntJanus** [comment]
This is interesting. I'm running my site on a 1gb DO and a few days ago I got a spike of 50K users within a day and the site was ultra-responsive. Never had to use a swap file and never got into any trouble with it but I'm guessing this is because the traffic was all to one page. 

Awesome idea though! Can't wait to add it to my site provisioning! :)

**Comment by EvanK** [comment]
Good news! I've refactored the defaults/vars for customizing swapfile settings in such a way that this PR should no longer require regeneration or a minor version bump (just a patch version)!

**Pull request merged**
