### PR TITLE
Preliminary improved documentation

### PR DESCRIPTION
**Pull request by EvanK**

### CODE REVIEW

**Comment by jimmynotjim** [comment]
It's...alive :D

**Comment by AntJanus** [comment]
This is awesome! I'd love to see an upgrade path from genesis/wordpress

**Comment by EvanK** [comment]
Even for this preliminary rewrite, I'm already seeing several pieces that need to be broken out into their own page and elaborated _a lot_.

@AntJanus That's on the roadmap, but will have its own obstacles I'm sure!

**Comment by EvanK** [comment]
Merging the docs as-is, so we have something more useful than "WIP" on master. I will continue to improve docs and open a new PR as I go

**Pull request merged**
