### PR TITLE
Permissions issue on rsync to remote

### PR DESCRIPTION
**Pull request by EvanK**
I'm getting this error on `bundle exec cap staging evolve:up:files`. It uploaded the files, so I'm not sure if this is a problem.

List of files uploaded, and then:
```
sent 55,493 bytes  received 131,803 bytes  124,864.00 bytes/sec
total size is 67,628,076  speedup is 361.08
vagrant stderr: rsync: failed to set times on "/var/www/example.com/staging/states-refresh/current/web/wp-content/uploads/2015": Operation not permitted (1)
rsync: failed to set times on "/var/www/example.com/staging/states-refresh/current/web/wp-content/uploads/2015/07": Operation not permitted (1)
rsync: failed to set times on "/var/www/example.com/staging/states-refresh/current/web/wp-content/uploads/2015/08": Operation not permitted (1)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/command.rb:97:in `exit_status='
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:56:in `block in _execute'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:37:in `tap'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:37:in `_execute'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:26:in `execute'
/Users/germanny/Sites/Example.com/bower_components/evolution-wordpress/lib/capistrano/tasks/files.rake:60:in `block (5 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:14:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/local.rb:14:in `run'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/dsl.rb:10:in `run_locally'
/Users/germanny/Sites/Example.com/bower_components/evolution-wordpress/lib/capistrano/tasks/files.rake:59:in `block (4 levels) in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Library/Ruby/Gems/2.0.0/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => evolve:files:up
(See full trace by running task with --trace)
```

### CODE REVIEW

**Comment by mcheck** [comment]
I have been having this issue for a while and glad I found it here already underway! I tested the capistrano changes and they work very well pushing to a remote server.

Altering the uploads owner to `deploy` seems a good solution. Thanks!

**Comment by EvanK** [comment]
@mcheck Thank _you_ for verifying it fixes the issue! I tested it myself, of course, but I like to have at least one other person confirming :grinning: 

I'll get this merged & released ASAP

**Comment by mcheck** [comment]
You're welcome! Glad to help out.

A question regarding process. I noticed the branch `80-rsync-permissions-owner` has other edits like `b47486e` that do not appear to have anything to do with the permissions issue. Is that because they were merged in from master from other edits?

Just making sure because I did not test that particular change as it has to do with Yeoman and original app creation.

Cheers!

**Comment by EvanK** [comment]
@mcheck Yes, those were just me keeping this branch up to date with master

**Pull request merged**
