### PR TITLE
fix file permissions after each sync or deployment

### PR DESCRIPTION
**Pull request by jalevin**
Various parts of the deployment messed with file permissions that caused problems when uploading files using gravity forms. I this commit simply runs evolve:permissions after deployment or whenever files are synced with evolve:up

### CODE REVIEW

**Comment by EvanK** [comment]
Thanks for this, I can get it rolled into the next release!

**Comment by jalevin** [comment]
Following up, this does not actually fix the problem. I am still tracking down the culprit, however, in the meantime, I added a line to explicitly set the uploads directory to be writeable. I'll follow up with another pull request.

**Comment by jalevin** [comment]
bump. can you take another look at this?

**Comment by EvanK** [comment]
I'm not certain what permissions issue you were encountering, but this looks like a simple enough change:

* enforces `www-data` group as well as `deploy` owner, for all wp-content subdirectories
* enforces group writable permission for uploads subdirectories

We can get this merged 👍

**Comment by jalevin** [comment]
Specifically Gravity forms was running into permissions errors when uploading files and when I started investigating permissions, it looked like any plugins that upload files would encounter this issue.

Thanks!!

**Comment by EvanK** [comment]
Tagged & released as [v1.4.4](https://github.com/evolution/wordpress/releases/tag/v1.4.4)

**Pull request merged**
