### PR TITLE
[HOLD] Dockerized local stage

### PR DESCRIPTION
**Pull request by EvanK**
This implements an alternative to a running vagrant machine for local development, via [Docker Compose](https://docs.docker.com/compose/) and [a pre-built container](https://hub.docker.com/r/evanskaufman/evolution-wordpress/).

### CODE REVIEW

**Comment by ericclemmons** [comment]
Now I know why I missed this: I was nearly dead!

**Comment by ericclemmons** [comment]
@EvanK I took a look over this & I think it's great progress!  It'd be worth having a convo over EOL'ing Genesis & Evolution in favor of an alternative, and this is lending credence of WordPress potentially having an app-like dev cycle.

A few of the topics & roles to discuss are:

- Yeoman
- Starting development
- Daily workflow
- Updating the project
- Provisioning
- Deployment

**Comment by EvanK** [comment]
FWIW, Genesis is already EOL (but for the occasional backported security fix)

**Comment by EvanK** [comment]
Closing this out -- we're working on another wordpress+docker approach, but it's tied to specific hardware (aws) & infrastructure (rancher) and we are unlikely to open source it any time soon

**Pull request closed without merging**
